import {
  LuLayoutDashboard,
  LuUsers,
  LuClipboardCheck,
  LuLogOut,
  LuUser,
  LuGraduationCap,
  LuUserCheck,
  LuBookOpen,
  LuCalendar,
  LuFileText,
  LuDollarSign,
  LuBus,
  LuHouse,
  LuMessageSquare,
  LuMegaphone,
  LuSettings,
  LuClipboardList,
  LuAward,
  LuLibrary,
  LuAlarmClock,
  LuTrendingUp,
  LuSchool,
  LuBell,
} from "react-icons/lu";

export const MENU_DATA = [
  {
    id: "01",
    label: "Dashboard",
    icon: LuLayoutDashboard,
    path: "/dashboard",
    visible: [
      "super_admin",
      "admin",
      "principal",
      "teacher",
      "student",
      "parent",
      "accountant",
      "librarian",
      "receptionist",
    ],
  },
  {
    id: "02",
    label: "Students",
    icon: LuGraduationCap,
    path: "/students",
    visible: ["admin", "principal", "teacher"],
  },
  {
    id: "03",
    label: "Teachers",
    icon: LuUserCheck,
    path: "/teachers",
    visible: ["admin", "principal"],
  },
  {
    id: "04",
    label: "Parents",
    icon: LuUsers,
    path: "/parents",
    visible: ["admin", "principal"],
  },
  {
    id: "05",
    label: "Classes",
    icon: LuSchool,
    path: "/classes",
    visible: ["admin", "principal", "teacher"],
  },
  {
    id: "06",
    label: "Subjects",
    icon: LuBookOpen,
    path: "/subjects",
    visible: ["admin", "principal"],
  },
  {
    id: "07",
    label: "Timetable",
    icon: LuCalendar,
    path: "/timetable",
    visible: ["admin", "principal", "teacher", "student"],
  },
  {
    id: "08",
    label: "Attendance",
    icon: LuClipboardCheck,
    path: "/attendance",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "09",
    label: "Exams",
    icon: LuFileText,
    path: "/exams",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "10",
    label: "Results",
    icon: LuAward,
    path: "/results",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "11",
    label: "Homework",
    icon: LuClipboardList,
    path: "/homework",
    visible: ["teacher", "student", "parent"],
  },
  {
    id: "12",
    label: "Fees",
    icon: LuDollarSign,
    path: "/fees",
    visible: ["admin", "accountant", "student", "parent"],
  },
  {
    id: "13",
    label: "Library",
    icon: LuLibrary,
    path: "/library",
    visible: ["admin", "librarian", "teacher", "student"],
  },
  {
    id: "14",
    label: "Transport",
    icon: LuBus,
    path: "/transport",
    visible: ["admin", "student", "parent"],
  },
  {
    id: "15",
    label: "Hostel",
    icon: LuHouse,
    path: "/hostel",
    visible: ["admin", "student"],
  },
  {
    id: "16",
    label: "Events",
    icon: LuCalendar,
    path: "/events",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "17",
    label: "Announcements",
    icon: LuMegaphone,
    path: "/announcements",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "18",
    label: "Messages",
    icon: LuMessageSquare,
    path: "/messages",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "19",
    label: "Complaints",
    icon: LuAlarmClock,
    path: "/complaints",
    visible: ["admin", "principal", "teacher", "student", "parent"],
  },
  {
    id: "20",
    label: "Certificates",
    icon: LuFileText,
    path: "/certificates",
    visible: ["admin", "principal", "student", "parent"],
  },
  {
    id: "21",
    label: "Leave",
    icon: LuClipboardCheck,
    path: "/leave",
    visible: ["admin", "principal", "teacher", "student"],
  },
  {
    id: "22",
    label: "Expenses",
    icon: LuTrendingUp,
    path: "/expenses",
    visible: ["admin", "accountant"],
  },
  {
    id: "23",
    label: "Notifications",
    icon: LuBell,
    path: "/notifications",
    visible: [
      "super_admin",
      "admin",
      "principal",
      "teacher",
      "student",
      "parent",
      "accountant",
      "librarian",
      "receptionist",
    ],
  },
  {
    id: "24",
    label: "My Profile",
    icon: LuUser,
    path: "/profile",
    visible: [
      "super_admin",
      "admin",
      "principal",
      "teacher",
      "student",
      "parent",
      "accountant",
      "librarian",
      "receptionist",
    ],
  },
  {
    id: "25",
    label: "Settings",
    icon: LuSettings,
    path: "/settings",
    visible: ["admin", "principal"],
  },
  {
    id: "26",
    label: "Logout",
    icon: LuLogOut,
    path: "logout",
    visible: [
      "super_admin",
      "admin",
      "principal",
      "teacher",
      "student",
      "parent",
      "accountant",
      "librarian",
      "receptionist",
    ],
  },
];
